### ISSUE TITLE
Tree does not have pre-computed hashes

### ISSUE THREAD

**Issue by slvrfn** [rugpullindex/indexed-sparse-merkle-tree#33]
It appears the code for pre-computing the hashes was removed, and the `get(uint256 level)` function mentioned in the readme, does not exist

**Comment by TimDaub** [comment]
yes, the readme is sadly out of date. But the tree implementation actually progressed so that it became more gas efficient.

**Comment by TimDaub** [comment]
https://github.com/rugpullindex/indexed-sparse-merkle-tree/commit/eacc9e4291c071f7d6bed607888e31de0fcfccab

**Comment by TimDaub** [comment]
source for optimization: https://ethresear.ch/t/optimizing-sparse-merkle-trees/3751/7

**Comment by slvrfn** [comment]
ah, thank you for the explanation! i agree this is an optimization
